dist: trusty
sudo: false
language: c
compiler: gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - make test
  - ls
  - cd bin
  - ls
  - ./test*